#!/usr/bin/env bash
set -euo pipefail

# Usage: (optional) export SUPABASE_URL="https://....supabase.co" SUPABASE_ANON_KEY="sb_publishable_..." 
# then run: ./setup_supabase_all.sh

echo "=== Starting Supabase auth setup (all-in-one) ==="

# 0: branch
BRANCH="fix/static-assets-for-vercel"
git rev-parse --verify "$BRANCH" >/dev/null 2>&1 && git checkout "$BRANCH" || git checkout -b "$BRANCH"

# 1: ensure directories
mkdir -p sql scripts public/js public/css public/images

# 2: create SQL
cat > sql/create_profiles.sql <<'SQL'
-- create_profiles.sql
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  username text unique,
  phone text,
  role text,
  created_at timestamptz default now()
);
create unique index if not exists profiles_username_idx on public.profiles(username);
SQL
echo "Wrote sql/create_profiles.sql"

# 3: build helper that writes public/js/config.js from environment (for Vercel)
cat > scripts/write-supabase-config.sh <<'SHL'
#!/usr/bin/env bash
set -e
if [ -z "${SUPABASE_URL:-}" ] || [ -z "${SUPABASE_ANON_KEY:-}" ]; then
  echo "ERROR: SUPABASE_URL or SUPABASE_ANON_KEY not set in environment. Aborting."
  exit 1
fi
mkdir -p public/js
cat > public/js/config.js <<EOF
// Auto-generated by scripts/write-supabase-config.sh
export const SUPABASE_URL = "${SUPABASE_URL}";
export const SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}";
EOF
echo "Wrote public/js/config.js"
SHL
chmod +x scripts/write-supabase-config.sh
echo "Created scripts/write-supabase-config.sh (make sure Vercel runs it during build)"

# 4: config.js — if environment variables exist, write it now for local testing; otherwise write placeholder
if [ -n "${SUPABASE_URL:-}" ] && [ -n "${SUPABASE_ANON_KEY:-}" ]; then
  cat > public/js/config.js <<EOF
// Auto-generated for local testing
export const SUPABASE_URL = "${SUPABASE_URL}";
export const SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}";
EOF
  echo "Wrote public/js/config.js from environment variables."
else
  cat > public/js/config.js <<'EOF'
/*
  public/js/config.js -- Replace placeholders with your Supabase values
  Example:
    export const SUPABASE_URL = "https://yourproject.supabase.co";
    export const SUPABASE_ANON_KEY = "sb-publishable_XXXXXXXXXXXX";
*/
export const SUPABASE_URL = "https://REPLACE_WITH_YOUR_PROJECT.supabase.co";
export const SUPABASE_ANON_KEY = "sb-publishable_REPLACE_ME";
EOF
  echo "Wrote public/js/config.js with placeholders. Set SUPABASE_URL & SUPABASE_ANON_KEY or run scripts/write-supabase-config.sh in your build."
fi

# 5: write auth.js
cat > public/js/auth.js <<'JS'
/*
  public/js/auth.js  — improved front-end auth for Supabase
  Expects /js/config.js exporting SUPABASE_URL and SUPABASE_ANON_KEY
*/
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '/js/config.js';
import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm';

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

function makeToastContainer() {
  if (document.getElementById('vasudha-toast-container')) return;
  const c = document.createElement('div');
  c.id = 'vasudha-toast-container';
  Object.assign(c.style, { position:'fixed', right:'18px', top:'18px', zIndex:99999, display:'flex', flexDirection:'column', gap:'10px' });
  document.body.appendChild(c);
}
function toast(msg, type='info', timeout=4500){
  makeToastContainer();
  const el = document.createElement('div');
  el.textContent = msg;
  el.style.padding = '10px 14px';
  el.style.borderRadius = '10px';
  el.style.boxShadow = '0 6px 18px rgba(0,0,0,0.12)';
  el.style.fontSize = '14px';
  el.style.color = (type==='danger')? '#fff' : '#07250f';
  el.style.background = (type==='danger')? '#c0392b' : (type==='success')? '#2ecc71' : '#f0f4ef';
  document.getElementById('vasudha-toast-container').appendChild(el);
  setTimeout(()=> el.remove(), timeout);
}
function setBusy(btn, busy=true){
  if(!btn) return;
  btn.disabled = busy;
  if(busy){ btn.dataset.orig = btn.innerHTML; btn.innerHTML = 'Please wait…'; btn.style.opacity='0.7'; }
  else { if(btn.dataset.orig) btn.innerHTML = btn.dataset.orig; btn.style.opacity='1'; }
}

async function handleRegister(e){
  e.preventDefault();
  const form = e.target;
  const first = (form.querySelector('#first')?.value||'').trim();
  const last = (form.querySelector('#last')?.value||'').trim();
  const email = (form.querySelector('#email')?.value||'').trim();
  const password = (form.querySelector('#password1')?.value||'').trim();
  const phone = (form.querySelector('#phone')?.value||'').trim();
  const username = (form.querySelector('#usernameReg')?.value||'').trim();
  const role = (form.querySelector('#accountType')?.value||'buyer').trim();
  const btn = form.querySelector('button[type="submit"]');
  if(!first||!email||!password){ toast('Please fill required fields.', 'danger'); return; }
  setBusy(btn, true);
  try{
    const { data, error } = await supabase.auth.signUp({ email, password });
    if(error) throw error;
    const user = data?.user;
    const full_name = `${first} ${last}`.trim();
    if(user && user.id){
      const { error: pErr } = await supabase.from('profiles').insert([{ id: user.id, full_name, username: username||null, phone: phone||null, role }]);
      if(pErr){ console.warn('profile err', pErr); toast('Registered but profile save failed.', 'danger'); setBusy(btn,false); return; }
      toast('Registration successful. Redirecting to login...', 'success', 2000);
      setTimeout(()=> window.location.href = '/login.html', 1200);
    } else {
      toast('Registration submitted. Please check your email to confirm (if required).', 'info', 7000);
    }
  }catch(err){
    console.error('register error', err);
    toast(err?.message || 'Registration failed', 'danger');
  }finally{ setBusy(btn,false); }
}

async function handleLogin(e){
  e.preventDefault();
  const form = e.target;
  const identifier = (form.querySelector('#username')?.value||'').trim();
  const password = (form.querySelector('#password')?.value||'').trim();
  const btn = form.querySelector('button[type="submit"]');
  if(!identifier||!password){ toast('Please enter email and password.', 'danger'); return; }
  setBusy(btn, true);
  try{
    let emailToUse = identifier;
    if(!identifier.includes('@')){
      const { data: rows } = await supabase.from('profiles').select('id, username').eq('username', identifier).limit(1);
      if(rows && rows.length){ toast('Please login with the email used during registration.', 'info', 6000); setBusy(btn,false); return; }
    }
    const { data, error } = await supabase.auth.signInWithPassword({ email: emailToUse, password });
    if(error) throw error;
    const session = data?.session || data;
    const user = session?.user;
    if(!user){ toast('Login succeeded but session missing.', 'info'); setBusy(btn,false); return; }
    const { data: profile } = await supabase.from('profiles').select('*').eq('id', user.id).single();
    const role = profile?.role || 'buyer';
    toast('Login successful. Redirecting...', 'success', 1200);
    setTimeout(()=> {
      if(role==='admin') window.location.href = '/admin/index.html';
      else if(role==='verifier') window.location.href = '/verifier.html';
      else if(role==='field_user') window.location.href = '/field-user.html';
      else window.location.href = '/buyer.html';
    },900);
  }catch(err){
    console.error('login error', err);
    toast(err?.message || 'Login failed', 'danger');
  }finally{ setBusy(btn,false); }
}

async function checkSessionProtect(){
  const { data } = await supabase.auth.getSession();
  const s = data?.session || null;
  if(!s){ window.location.href = '/login.html'; return false; }
  return true;
}

function init(){
  const reg = document.getElementById('registerForm'); if(reg) reg.addEventListener('submit', handleRegister);
  const login = document.getElementById('loginForm'); if(login) login.addEventListener('submit', handleLogin);
  makeToastContainer();
}
document.addEventListener('DOMContentLoaded', init);

window._vasudha_supabase = { supabase, handleRegister, handleLogin, checkSessionProtect };
JS

echo "Wrote public/js/auth.js"

# 6: user-register.html
cat > public/user-register.html <<'HTML'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>User Registration — Vasudha</title>
  <style>
    :root{--accent:#2f6b3a;--muted:#f1f6f1}
    body{font-family: Georgia, serif; background: #f8fbf8; color:#063014; margin:0; padding:24px; display:flex; align-items:center; justify-content:center; min-height:100vh}
    .card{width:920px;max-width:96%;background:#fff;border-radius:16px;padding:24px;box-shadow:0 10px 28px rgba(3,10,7,0.06)}
    h1{font-size:28px;margin-bottom:8px}
    p.lead{color:#3b5a3f;margin-bottom:18px}
    .grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
    label{display:block;font-weight:700;margin-bottom:6px}
    input,select,textarea{width:100%;padding:12px 14px;border-radius:12px;border:1px solid #e6efe6;background:var(--muted);font-size:15px}
    .actions{display:flex;gap:12px;justify-content:center;margin-top:18px}
    .btn{background:linear-gradient(#2f6b3a,#244f2d);color:#fff;padding:12px 28px;border-radius:12px;border:none;font-weight:700;cursor:pointer}
    .btn.ghost{background:transparent;border:2px solid #dcdcdc;color:#333}
    .small{font-size:13px;color:#546a56}
    .muted{color:#6b8b74}
    .center{grid-column:1/-1;display:flex;gap:12px;align-items:center}
    @media(max-width:880px){ .grid{grid-template-columns:1fr} .center{flex-direction:column} }
  </style>
</head>
<body>
  <main class="card" role="main" aria-labelledby="regTitle">
    <h1 id="regTitle">Create your Vasudha account</h1>
    <p class="lead">Sign up to manage projects, buy credits and participate in MRV workflows.</p>

    <form id="registerForm" autocomplete="on" novalidate>
      <div class="grid">
        <div>
          <label for="first">First Name *</label>
          <input id="first" name="first" type="text" required placeholder="First name">
        </div>

        <div>
          <label for="last">Last Name</label>
          <input id="last" name="last" type="text" placeholder="Last name">
        </div>

        <div>
          <label for="email">Email *</label>
          <input id="email" name="email" type="email" required placeholder="you@example.com">
        </div>

        <div>
          <label for="usernameReg">Username (optional)</label>
          <input id="usernameReg" name="usernameReg" type="text" placeholder="username (for display)">
        </div>

        <div>
          <label for="password1">Password *</label>
          <input id="password1" name="password1" type="password" required placeholder="Choose a strong password">
        </div>

        <div>
          <label for="phone">Phone</label>
          <input id="phone" name="phone" type="tel" placeholder="+91 98765 43210">
        </div>

        <div class="center">
          <div style="flex:1">
            <label for="accountType">Account Type</label>
            <select id="accountType" name="accountType">
              <option value="buyer">Buyer</option>
              <option value="project_owner">Project Owner</option>
              <option value="verifier">Verifier</option>
              <option value="field_user">Field User</option>
              <option value="admin">Admin</option>
            </select>
            <div class="small muted">Choose the role that suits you. For admin access you will need manual approval.</div>
          </div>
        </div>

      </div>

      <div style="margin-top:12px">
        <label style="display:flex;align-items:center;gap:8px;font-weight:600">
          <input type="checkbox" id="agree" required> I agree to the <a href="#" style="color:var(--accent)">privacy policy</a>
        </label>
      </div>

      <div class="actions">
        <button type="submit" class="btn">Create account</button>
        <a href="/login.html" class="btn ghost" role="button">Already have an account</a>
      </div>

      <p class="small muted" style="text-align:center;margin-top:12px">This site uses Supabase for authentication & profile storage.</p>
    </form>
  </main>

  <script type="module" src="/js/auth.js"></script>
</body>
</html>
HTML

# 7: login.html
cat > public/login.html <<'HTML'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Login — Vasudha</title>
  <style>
    body{font-family:Georgia,serif;background:#f6fbf6;color:#063014;margin:0;display:flex;align-items:center;justify-content:center;min-height:100vh;padding:20px}
    .card{width:760px;max-width:96%;background:#fff;border-radius:16px;padding:28px;box-shadow:0 12px 36px rgba(0,0,0,0.06)}
    h2{font-size:28px;margin:0 0 12px}
    .input{display:flex;flex-direction:column;gap:6px;margin-bottom:12px}
    input{padding:12px 14px;border-radius:12px;border:1px solid #e6efe6;background:#f4faf4;font-size:15px}
    .actions{display:flex;gap:12px;align-items:center}
    .btn{background:linear-gradient(#2f6b3a,#244f2d);color:#fff;padding:12px 18px;border-radius:12px;border:none;font-weight:700;cursor:pointer}
    .muted{color:#6b8b74;font-size:14px}
    .links{display:flex;gap:8px;justify-content:flex-end}
    @media(max-width:560px){ .card{padding:18px} }
  </style>
</head>
<body>
  <main class="card" role="main" aria-labelledby="loginTitle">
    <h2 id="loginTitle">Welcome back — sign in</h2>
    <p class="muted">Log in with the email you used to register.</p>

    <form id="loginForm" autocomplete="on" novalidate>
      <div class="input">
        <label for="username">Email</label>
        <input id="username" name="username" type="email" placeholder="you@example.com" required>
      </div>

      <div class="input">
        <label for="password">Password</label>
        <input id="password" name="password" type="password" placeholder="Enter password" required>
      </div>

      <div style="display:flex;justify-content:space-between;align-items:center;margin-top:8px">
        <div class="links"><a href="/user-register.html" style="text-decoration:none;color:#2f6b3a">Create account</a></div>
        <div><button type="submit" class="btn">Sign in</button></div>
      </div>
    </form>
  </main>

  <script type="module" src="/js/auth.js"></script>
</body>
</html>
HTML

# 8: stage, commit, push
git add sql scripts public/js public/user-register.html public/login.html || true
git commit -m "Add Supabase auth setup: SQL, build helper, config, auth.js, login & register pages" || echo "Nothing to commit"
git push -u origin HEAD || echo "git push failed - run 'git push' manually"

# 9: final notes
echo "=== DONE ==="
echo "If you didn't export SUPABASE_URL & SUPABASE_ANON_KEY before running, open public/js/config.js and replace placeholders with real values."
echo "Run SQL in Supabase SQL editor: sql/create_profiles.sql"
echo "If deploying to Vercel, add env vars SUPABASE_URL & SUPABASE_ANON_KEY and set build command to: bash scripts/write-supabase-config.sh && (your-build-if-any)."
echo "Test locally: cd public && python3 -m http.server 8000  -> http://localhost:8000/user-register.html"
