#!/usr/bin/env bash
# scripts/write-supabase-config.sh
# This writes public/js/config.js using environment variables:
#   SUPABASE_URL
#   SUPABASE_ANON_KEY
# Vercel: add a build step to run this script before publishing (see README below).

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "ERROR: SUPABASE_URL or SUPABASE_ANON_KEY not set in environment."
  exit 1
fi

cat > public/js/config.js <<EOF
// Auto-generated by scripts/write-supabase-config.sh
export const SUPABASE_URL = "${SUPABASE_URL}";
export const SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}";
EOF

echo "Wrote public/js/config.js"
