#!/usr/bin/env bash
set -e
if [ -z "${SUPABASE_URL:-}" ] || [ -z "${SUPABASE_ANON_KEY:-}" ]; then
  echo "ERROR: SUPABASE_URL or SUPABASE_ANON_KEY not set in environment. Aborting."
  exit 1
fi
mkdir -p public/js
cat > public/js/config.js <<EOF
// Auto-generated by scripts/write-supabase-config.sh
export const SUPABASE_URL = "${SUPABASE_URL}";
export const SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}";
EOF
echo "Wrote public/js/config.js"
